### ISSUE TITLE
Configuración del plan de versiones 

### ISSUE THREAD

**Issue by JorgeArroyo33** [JorgeArroyo33/ISO2-2023-B04#11]

**Comment by JorgeArroyo33** [comment]
Tras discutir entre todos como íbamos a configurar las distintas versiones de nuestro proyecto lo hemos documentado en la sección de la wiki [Versiones](https://github.com/JorgeArroyo33/ISO2-2023-B04/wiki/Configuraci%C3%B3n-Del-Plan#3-versiones)  donde vemos la nomenclatura que tendrán nuestras versiones a lo largo del proyecto

**Comment by SergiooCoorne** [comment]
Después de decidir la configuración de las distintas versiones del proyecto, no pusimos a decidir como iba a ser el plan de lanzamiento del proyecto, quedando como esta puesto actualmente en [Versiones](https://github.com/JorgeArroyo33/ISO2-2023-B04/wiki/Configuraci%C3%B3n-Del-Plan#3-versiones)

**Comment by JorgeArroyo33** [comment]
Tras la retroalimentación de la sesión que tuvimos con el profesor decidimos cambiar el punto de vista de como íbamos a gestionar las versiones por lo que actualizamos la parte de la [wiki](https://github.com/JorgeArroyo33/ISO2-2023-B04/wiki/Configuraci%C3%B3n-Del-Plan#3-versiones)
