### ISSUE TITLE
Configuración de las Issues y ramas 

### ISSUE THREAD

**Issue by JorgeArroyo33** [JorgeArroyo33/ISO2-2023-B04#12]

**Comment by AntonioGomez03** [comment]
La gestión de ´issues` se realizará de la siguiente manera:

- Cada vez que se cree una, se asignará a los miembros del equipo que se haya acordado en las reuniones.
- Cada `issue` tendrá una etiqueta que identificará cuál es su objetivo principal. Algunas de ellas son: configuración, requisitos, casos de uso, etc..
-  Se intentará revisar periódicamente el trabajo realizado de cada `issue` por aquellos miembros a los que no se les haya asignado esta, con la finalidad de corregir posibles fallos.

**Comment by AntonioGomez03** [comment]
En cuanto a las ramas creadas, existirán 4 tipos principalmente:

- Main (rama develop): En la rama principal, se almacenará todo el código generado en cada una de las iteraciones del proyecto. 

- Ramas de iteración: En estas ramas, se almacenará el código generado por cada iteración, es decir, no será una rama acumulativa como si que lo es la rama `main`. Estas ramas se crearán al principio de cada iteración desde la rama `main`. Para ello, se seguirán las instrucciones mencionadas en la wiki.

- Documentacion: Esta rama estará aislada del resto. Se almacenará toda los archivos de Visual Paradigm (.vpp) generados en las etapas de cada una de las iteraciones.

- Master: En esta rama se almacenarán todo el código listo para ser desplegado.

**Comment by JorgeArroyo33** [comment]
Tras la retroalimentación de la sesión que tuvimos con el profesor decidimos cambiar el punto de vista de como íbamos a gestionar las ramas por lo que actualizamos la parte de la [wiki](https://github.com/JorgeArroyo33/ISO2-2023-B04/wiki/Configuraci%C3%B3n-Del-Plan#2-definici%C3%B3n-de-ramas)
