### ISSUE TITLE
Diagramas de casos de uso de los sistemas

### ISSUE THREAD

**Issue by JorgeArroyo33** [JorgeArroyo33/ISO2-2023-B04#13]

**Comment by cordobahhhh** [comment]
Una duda que hemos tenido a la hora de hacer los casos de uso ha sido que no sabemos si conectar cada caso de uso de un usuario conectarlo con el propio servidor o no. Por ello procederemos a consultarlo con los demas comoponentes del equipo el proximo dia en la reunion.

**Comment by cordobahhhh** [comment]
Hemos detectado que nos falta poner en la descripcion de los requisitos de asistentes de eventos el confirmacion de asistencia que en el mapeado si lo teniamos, hemos procedido a arreglarlo en la wiki.
