### ISSUE TITLE
Uso de la herramienta Maven 

### ISSUE THREAD

**Issue by JorgeArroyo33** [JorgeArroyo33/ISO2-2023-B04#14]

**Comment by SergiooCoorne** [comment]
Como instalar Maven y añadir los plugins correspondientes quedó explicado en el apartado perteneciente a la Wiki de "Documentación"
https://github.com/JorgeArroyo33/ISO2-2023-B04/wiki/Documentaci%C3%B3n

**Comment by SergiooCoorne** [comment]
Como instalar Maven y añadir los plugins correspondientes quedó explicado en el apartado perteneciente a la Wiki de "Documentación"
https://github.com/JorgeArroyo33/ISO2-2023-B04/wiki/Documentaci%C3%B3n
