### ISSUE TITLE
Implentación + Testing It2

### ISSUE THREAD

**Issue by AntonioGomez03** [JorgeArroyo33/ISO2-2023-B04#33]
Inicio 📆: 05/12/2023
Fin 📆: 07/12/2023
Objetivo 🎯: Finalizar la fase de implementacion y testing correspondiente a la iteración 2.
Equipo de trabajo 💻: @JorgeArroyo33 @SergiooCoorne

**Comment by JorgeArroyo33** [comment]
Una vez implementado tanto el lado del usuario como el lado del servidor podemos subir la implementacion
