### ISSUE TITLE
Error en el establecimiento de prioridad de las iteraciones 5 y 7.

### ISSUE THREAD

**Issue by agijon18** [JorgeArroyo33/ISO2-2023-B04#40]
Nos hemos dado cuenta de que la iteración 7 tiene que estar antes que la 5, sería hacer lo mismo pero cambiando el orden, primero diseñamos la 7 (pasaría a ser la 5) y después la 5 (que pasaría a ser la 7). 

El error está en que para que los asistentes puedan solicitar un certificado (y confirmar la llegada del mismo), primero debe haberse generado dicho certificado.

Nos hemos dado cuenta antes de que tengamos que diseñar la iteración 5, así que cambiaremos las prioridades y diseñaremos primero lo que a día de hoy es nuestra iteración 7, pero que tras la corrección pasa a ser la 5 y la 5 pasa a ser la 7. 
En resumidas cuentas, cambiaremos el orden en el que las diseñamos.

**Comment by AntonioGomez03** [comment]
He estado revisándolo y estoy de acuerdo. No tiene sentido gestionar algo que aún no se ha creado.

**Comment by AntonioGomez03** [comment]
El cambio se ha realizado. [Commit del cambio en la Wiki](https://github.com/JorgeArroyo33/ISO2-2023-B04/wiki/Iteraci%C3%B3n-0-UDP/6340aa51fc1718fc800827712d6e5b5ac3b64fa3)
