### ISSUE TITLE
Implementación + Test It3

### ISSUE THREAD

**Issue by AntonioGomez03** [JorgeArroyo33/ISO2-2023-B04#41]
Inicio 📆: 07/12/2023
Fin 📆: 12/12/2023
Objetivo 🎯: Finalizar la fase de implementación y testing correspondiente a la iteración 3.
Equipo de trabajo 💻: @JorgeArroyo33 @SergiooCoorne

**Comment by SergiooCoorne** [comment]
Debido a los errores encontrados en el diseño de diagramas, la implementación se subió de forma errónea, teniendo ya que corregir la forma en la que se realizan las implementaciones en futuras iteraciones.
