### ISSUE TITLE
Diseño it5

### ISSUE THREAD

**Issue by cordobahhhh** [JorgeArroyo33/ISO2-2023-B04#53]
Inicio 📆: 12/12/2023
Fin 📆:   13/12/2023
Objetivo 🎯: Finalizar la fase de diseño correspondiente a la iteración 5.
Equipo de trabajo 💻: @AntonioGomez03  @cordobahhhh  @agijon18

**Comment by AntonioGomez03** [comment]
A la hora de hacer el diagrama de clases de diseño del sistema `Organizador`, nos hemos dado cuenta de que el JFrameFirmaCertificado no sería necesario. 

- **Motivo**: Al solicitar la generación de certificados, estos se firmarán automáticamente en el lado del cliente, por lo que no haría falta una ventana especialmente diseñada para firmar.
