### ISSUE TITLE
Implementacion + Testing It5

### ISSUE THREAD

**Issue by AntonioGomez03** [JorgeArroyo33/ISO2-2023-B04#56]
Inicio 📆: 13/12/2023
Fin 📆: 14/12/2023
Objetivo 🎯: Finalizar la fase de implementacion y testing correspondiente a la iteración 5.
Equipo de trabajo 💻: @SergiooCoorne @JorgeArroyo33

**Comment by SergiooCoorne** [comment]
Después de tener que subir varias veces el módulo ya que había conflictos con el Eclipse, se ha conseguido subir de manera correcta la implementación y se puede proceder a cerrar la Issue.
