### ISSUE TITLE
Mapear los requisitos funcionales a casos de uso 

### ISSUE THREAD

**Issue by JorgeArroyo33** [JorgeArroyo33/ISO2-2023-B04#6]

**Comment by AntonioGomez03** [comment]
El objetivo es mapear los requisitos funcionales a casos de uso.
Este issue no se podrá empezar hasta que se cierre [Especificar los requisitos funcionales](https://github.com/JorgeArroyo33/ISO2-2023-B04/issues/8).

**Comment by JuanCordoba69** [comment]
- Hemos decidido que `RF.O.03` y `RF.O.04`: Cuando se solicita la generación de certificados al servidor, el organizador de eventos deberá firmar digitalmente este. Es por ello, por lo que, hemos decidido mapear estos dos requisitos en el mismo caso de uso, ya que, la funcionalidad de estos es similar.

**Comment by daviddmunozzz** [comment]
* Hemos decidido juntar `RF.AE.03` y `RF.AE.04' , porque ambos tienen relación con la petición del certificado firmado. Además, una vez solicitado el certificado, el asistente podrá confirmar la recepción de este.
