### ISSUE TITLE
Prioridad de los casos de usos

### ISSUE THREAD

**Issue by JorgeArroyo33** [JorgeArroyo33/ISO2-2023-B04#7]
Nos encargaremos de establecer la aproximación de horas que vamos a tardar en cada caso de uso

**Comment by SergiooCoorne** [comment]
Después de ver que casos de uso dependen del orden de la implementación de otros, hemos asignado las prioridades de cada uno de ellos acorde a estos requisitos. 
Hemos puesto las iteraciones que creemos necesarias para la realización del proyecto agrupando los casos de usos que se tienen implementar a la vez en las mismas iteraciones. 
También hemos asignado las estimaciones de tiempo a las diferentes fases de RADIT basándonos en nuestro criterio sobre cuantas horas serian necesarias para hacer cada fase.

Se pueden ver los cambios realizados en la Wiki aquí: https://github.com/JorgeArroyo33/ISO2-2023-B04/wiki/Iteraci%C3%B3n-0-UDP/4625fa6384e54d690d0838a9c4db9d2f045f8147
