### ISSUE TITLE
Horas extras.

### ISSUE THREAD

**Issue by JuanCordoba69** [JorgeArroyo33/ISO2-2023-B04#72]
El día 16/12/2023 se llevará a cabo una reunión para aclarar algunas inconsistencias en los requisitos para mejorar la productividad a la hora de hacer el análisis y el diseño de los casos de uso.

**Comment by agijon18** [comment]
Finalmente no solo fue necesaria una reunión extra el día 16/12/2023, sino también otra el día 17/12/2023. 
En estas reuniones se discutió acerca de los requisitos, ya que había uno que estaban redactado de forma confusa, derivando en dificultades a la hora de realizar el análisis y diseño. Este error ha sido corregido.

Además, hemos detectado que en su día nos dejamos 3 requisitos de asistentes de eventos que son:
• Valorar un determinado evento, si el organizador del evento ha habilitado los
mecanismos de evaluación correspondientes. 
• Realizar distintos tipos de consultas, parametrizables sobre la asistencia o disponibilidad
de los diferentes tipos de evento, evento, o rango de fechas.
• Solicitar y recoger certificados de asistencia a los diferentes tipos de eventos. Se desea
dar la opción de solicitar un certificado por un conjunto de eventos docentes (p.ej.
certificado de asistencia a clases).

La decisión que hemos tomado como equipo ha sido añadir estos requisitos y hacerlos en las últimas iteraciones del proyecto, ya que no interfieren en otras funcionalidades del sistema y ponerlos entre medias supondría realizar muchos cambios en cascada.

Esto ha sido un error bastante grande, pero gracias a él hemos aprendido que cuando trabajemos en proyectos reales, debemos hacer especial hincapié en hacer una buena iteración 0, haciendo la mejor captura de requisitos posible y estableciendo bien las bases del proyecto desde el principio.
