### ISSUE TITLE
Especificar los requisitos funcionales 

### ISSUE THREAD

**Issue by JorgeArroyo33** [JorgeArroyo33/ISO2-2023-B04#8]

**Comment by AntonioGomez03** [comment]
Con el objetivo de entender los requisitos obtenidos en el issue [Obtención de requisitos](https://github.com/JorgeArroyo33/ISO2-2023-B04/issues/5), vamos a realizar una descripción detallada de cada uno de ellos. 
Esto nos permitirá poder realizar un mapeado y priorización de los Casos de Uso y creación de Grupos Funcionales de manera eficiente e informada.

**Comment by agijon18** [comment]
Se adjunta la primera versión de la especificación de requisitos funcionales del sistema:

[Explicación requisitos funcionales.md](https://github.com/JorgeArroyo33/ISO2-2023-B04/files/13242985/Explicacion.requisitos.funcionales.md)

**Comment by AntonioGomez03** [comment]
Se ha añadido la especificación de requisitos a la wiki. Este es el [enlace](https://github.com/JorgeArroyo33/ISO2-2023-B04/wiki/Iteraci%C3%B3n-0-UDP#2-requisitos-funcionales).

**Comment by AntonioGomez03** [comment]
He estado revisando los requisitos funcionales y he visto algunas cosas que quizás se puedan cambiar:

* En los requisitos comunes a todos los usuarios, hemos añadido el de `login` y el de `autenticar`. Sin embargo, a diferencia que en el resto de requisitos funcionales, no le hemos añadido ninguna letra sobre a que actor/sistema pertenece ese requisito. En el caso del `login` podríamos utilizar la nomenclatura `RF.U.X` (*U* de *Usuario*) y en el de `autenticar`, la nomenclatura `RF.S.X`.

* En el requisito `RF.O.02 (Abrir evento)`, no hemos explicado que la opción de geolocalizar el evento sirve para automatizar los datos informativos del evento. Además, quizás se pueda diferenciar en otro requisito funcional el hecho de `generar el código QR/número de asistencia` y el de `registrar asistencia usuarios` (ambos por parte del Servidor). 

* Muy relacionado con el punto anterior, faltaría añadir un requisito funcional a los asistentes de eventos para poder registrar su asistencia a un evento. Según el tipo de evento que sea (presencial u online), este registro se podrá hacer de 3 formas distintas: introduciendo un número, leyendo un código QR o mediante conexión Bluetooth del dispositivo del asistente. Además, esta información, correspondiente a la forma de registrar la asistencia, creo que se podría quitar de la especificación del requisito `RF.0.02 (Abrir evento)`.

**Comment by JuanCordoba69** [comment]
- Respecto a la observación anterior en total sería: cambiar `login` y `autenticator`, (uno lo hace cualquier usuario U y otro el servidor S), crear dos requisitos funcionales: `generar QR` y  `registrar asistencia de usuarios` (ambos requisitos son del servidor), y luego 3 requisitos funcionales de asistentes que son: poder asistir mediante escaneo QR, introduciendo un número o mediante conexión bluetooth (aunque estos tres últimos quizás se puedan incluir en uno solo)

**Comment by daviddmunozzz** [comment]
Respecto a los `RF.O.03` ,`RF.S.02`, `RF.O.04`, nosotros pensamos que solicitar y firmar podrían ir en el mismo CDU, porque al solicitar el sistema pedirá la firma y después generará el certificado. Dádnos vuestra opinión y documentádlo. @agijon18 @cordobahhhh

**Comment by agijon18** [comment]
Todos los cambios comentados por los compañeros han sido revisados y corregidos. Este es el nuevo documento generado:

[Especificación requisitos funcionales.md](https://github.com/JorgeArroyo33/ISO2-2023-B04/files/13261111/Especificacion.requisitos.funcionales.md)

Un par de consideraciones:
1) El requisito funcional de registrar asistencia de usuarios por parte del servidor se ha dejado marcado con un asterisco, pues lo teníamos marcado como supuesto (concretamente el supuesto número 2). Se deja pendiente para comentarlo en la próxima reunión.
2) Finalmente hemos decidido dejar como un solo requisito el hecho de registrar asistencia por parte de los asistentes de evento, pero seguimos teniendo dudas al respecto. Se comentará también en la próxima reunión.
3) Se han añadido a los títulos la abreviatura que hace referencia a cada tipo de usuario para entender mejor la nomenclatura.

En cuanto al último comentario de @daviddmunozzz, decir que también sería válido de esa manera. Son dos maneras distintas de hacerlo (presuntamente ambas válidas), solo hay que documentarlo e implementarlo correctamente. Este será también un tema a tratar en la próxima reunión, pensaremos en cuál de las dos opciones nos resulta más viable y lo documentaremos.
